---
services:
  vim:
    container_name: vim
    image: dceoy/vim:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: cli
      platforms:
        - linux/arm64
        - linux/amd64
      args:
        UBUNTU_VERSION: "24.04"
        PYTHON_VERSION: "3.13"
        USER_NAME: "cli"
        USER_UID: 1001
        USER_GID: 1001
      cache_from:
        - type=gha
      cache_to:
        - type=gha,mode=max
    user: ${UID}:${GID}
    userns_mode: host
    volumes:
      - .:/wd
    working_dir: /wd
    entrypoint:
      - /usr/local/bin/vim
    command:
      - --version
