---
services:
  vim:
    container_name: vim
    image: dceoy/vim:latest
    user: ${UID}:${GID}
    userns_mode: host
    volumes:
      - .:/wd
    working_dir: /wd
    entrypoint:
      - /usr/local/bin/vim
    command:
      - --version
