---
name: CI to Docker Hub
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build-and-push:
    uses: dceoy/gh-actions-for-devops/.github/workflows/docker-buildx-bake.yml@main
    with:
      registry: docker.io
      registry-user: ${{ github.actor }}
      bake-files: compose.yml
      push: true
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
